### PR TITLE
plain language version

### PR DESCRIPTION
**Pull request by pdurbin**
Replacing this...

 - The project or group that I represent has honorable intentions, meaning doing something that is primarily intended to benefit many people, or a community over any financial interest.
 - The project grew to be valued for its own utility without influence of artificial means, or unfair advantage.
 - The project or group strives to have minimal negative effects on the larger community. If negative effects are brought to light, a best effort is made to ameliorate them.

... with this...

 - The project or group that I represent is oriented toward sustainably helping people or advancing science rather than maximizing profits.
 - Marketing is done by the community rather than a corporate sponsor.
 - We have a code of conduct and will enforce it.

### CODE REVIEW

**Comment by vsoch** [comment]
These are great suggestions!  Just to clarify - the second bullet doesn't say that the project can't have corporate sponsorship (this is how I first read it). Is there a different way to say it that doesn't bring this to mind when read quickly? (it just happened to me).

**Comment by pdurbin** [comment]
In the pull request I changed the bullet to say this: "Marketing is done by the community rather than a corporate sponsor."

I started with the word "marketing" to try to make that the focus. I'm not trying to say that that projects shouldn't accept any money from corporations at all. LibrePlanet, the Free Software Foundation conference, is sponsored by Red Hat and others listed at https://libreplanet.org/2019/sponsors/ . I get the impression that Red Hat gives them money for food and such. I think this is fine. I'm trying to hone in on the marketing specifically. I'm thinking back to https://vsoch.github.io/2019/transparency/#1-community-is-different where you say this:

"The definition of community is different. Instead of a group of passionate linux nerds, these new communities come with branding, marketing departments, and flashy conferences with stickers and (more commonly) ticket prices going over 1K. You can create the illusion of a community if you can pay for it. People that participate in open source can’t really tell the difference, and so they will get excited too. It’s showing me a beautiful cake in the display window that I’ll never be able to taste, but I’ll take pictures of it and send to my friends because I believe that it tastes good."

Having one of the bullets be at least a bit anti-corporate works for me. Some of the artificiality comes from the marketing, perhaps. Open source projects should care about marketing but maybe the marketing can come from within, from the community. I guess that's what I'm suggesting.

Oh, and hopefully you noticed a put a little pro-science in there too. The first bullet. :smile:

**Comment by vsoch** [comment]
Do you think this has the appropriate level of teeth? Do you like it now?

**Comment by pdurbin** [comment]
It's not perfect but I think it's better.

When I think of maximizing profits, I think of Ms. Tweedy, the villain in Chicken Run.

When I think about the greater good, I think of Frozone in The Incredibles. He's one of the heroes. :smile:

**Comment by vsoch** [comment]
Let’s strive for @pdurbin level “love it.” What changes would you make so that you love it?

**Comment by pdurbin** [comment]
@vsoch I dunno, maybe we could incorporate some of the ideas from #23.

**Comment by vsoch** [comment]
Good idea @pdurbin, I especially like the list of words. What kind of bullets did you have in mind for the affirmation based on these ideas?

**Comment by pdurbin** [comment]
I'm not sure but I'm still thinking about what would make me love the Greater Good Affirmation. I just opened a couple issues:

-  open core #24 
-  paying for security updates #25 

I'm probably just thinking about my own preferences when it comes to software. I'm not a big fan of open core. I get grumpy when software is open source but you have to switch away from the "community" edition if you want to stay secure. @vsoch please feel free to close my pull requests and issues in this repo if I'm way off the mark in terms of what your intentions are with the Greater Good Affirmation. Thanks.

**Comment by vsoch** [comment]
You might be interested to join the conversation here https://github.com/sfosc/sfosc/issues/63#issuecomment-493591914. It's strange, I know what my intentions are for the Greater Good Affirmation, but I'm having a hard time quantifying it. Whatever metric we come up with, it intrinsically makes a statement that some kind of action is "evil" if it's not for the greater good, and people get thrown off. Maybe I'm trying to please too many people, or I haven't found the right points yet. The problem is that there is no universal "definition" for being for the greater good, it's about trust with a community, making decisions on behalf of that community, and existing for that.

**Comment by pdurbin** [comment]
@vsoch thanks, interesting conversation.

Now that @Dimitij-Polianin is offering to translate the site into Russian (!! :tada:) as part of #27 I'm wondering if he like the "plain language" version in this pull request or not. :smile: 

That said, I just looked at the affirmation as of e1e0534 and it's much better worded now than back when I made this pull request. So if you want, I can just close it (or you can).

**Comment by vsoch** [comment]
Thanks for the update @pdurbin, happy to close.

**Pull request closed without merging**
